// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared/messages/KVMessage.proto

package shared.messages;

public final class ProtoKVMessage {
  private ProtoKVMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KVProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shared.messages.KVProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 statusMsg = 1;</code>
     * @return The statusMsg.
     */
    int getStatusMsg();

    /**
     * <code>string keyMsg = 2;</code>
     * @return The keyMsg.
     */
    java.lang.String getKeyMsg();
    /**
     * <code>string keyMsg = 2;</code>
     * @return The bytes for keyMsg.
     */
    com.google.protobuf.ByteString
        getKeyMsgBytes();

    /**
     * <code>string valueMsg = 3;</code>
     * @return The valueMsg.
     */
    java.lang.String getValueMsg();
    /**
     * <code>string valueMsg = 3;</code>
     * @return The bytes for valueMsg.
     */
    com.google.protobuf.ByteString
        getValueMsgBytes();

    /**
     * <code>uint64 idMsg = 4;</code>
     * @return The idMsg.
     */
    long getIdMsg();
  }
  /**
   * <pre>
   * Defining the message format 
   * </pre>
   *
   * Protobuf type {@code shared.messages.KVProto}
   */
  public static final class KVProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:shared.messages.KVProto)
      KVProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KVProto.newBuilder() to construct.
    private KVProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KVProto() {
      keyMsg_ = "";
      valueMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KVProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KVProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              statusMsg_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              keyMsg_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              valueMsg_ = s;
              break;
            }
            case 32: {

              idMsg_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return shared.messages.ProtoKVMessage.internal_static_shared_messages_KVProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return shared.messages.ProtoKVMessage.internal_static_shared_messages_KVProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              shared.messages.ProtoKVMessage.KVProto.class, shared.messages.ProtoKVMessage.KVProto.Builder.class);
    }

    public static final int STATUSMSG_FIELD_NUMBER = 1;
    private int statusMsg_;
    /**
     * <code>uint32 statusMsg = 1;</code>
     * @return The statusMsg.
     */
    @java.lang.Override
    public int getStatusMsg() {
      return statusMsg_;
    }

    public static final int KEYMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object keyMsg_;
    /**
     * <code>string keyMsg = 2;</code>
     * @return The keyMsg.
     */
    @java.lang.Override
    public java.lang.String getKeyMsg() {
      java.lang.Object ref = keyMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string keyMsg = 2;</code>
     * @return The bytes for keyMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyMsgBytes() {
      java.lang.Object ref = keyMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUEMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object valueMsg_;
    /**
     * <code>string valueMsg = 3;</code>
     * @return The valueMsg.
     */
    @java.lang.Override
    public java.lang.String getValueMsg() {
      java.lang.Object ref = valueMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        valueMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string valueMsg = 3;</code>
     * @return The bytes for valueMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueMsgBytes() {
      java.lang.Object ref = valueMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        valueMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDMSG_FIELD_NUMBER = 4;
    private long idMsg_;
    /**
     * <code>uint64 idMsg = 4;</code>
     * @return The idMsg.
     */
    @java.lang.Override
    public long getIdMsg() {
      return idMsg_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (statusMsg_ != 0) {
        output.writeUInt32(1, statusMsg_);
      }
      if (!getKeyMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, keyMsg_);
      }
      if (!getValueMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, valueMsg_);
      }
      if (idMsg_ != 0L) {
        output.writeUInt64(4, idMsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (statusMsg_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, statusMsg_);
      }
      if (!getKeyMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, keyMsg_);
      }
      if (!getValueMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, valueMsg_);
      }
      if (idMsg_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, idMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof shared.messages.ProtoKVMessage.KVProto)) {
        return super.equals(obj);
      }
      shared.messages.ProtoKVMessage.KVProto other = (shared.messages.ProtoKVMessage.KVProto) obj;

      if (getStatusMsg()
          != other.getStatusMsg()) return false;
      if (!getKeyMsg()
          .equals(other.getKeyMsg())) return false;
      if (!getValueMsg()
          .equals(other.getValueMsg())) return false;
      if (getIdMsg()
          != other.getIdMsg()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUSMSG_FIELD_NUMBER;
      hash = (53 * hash) + getStatusMsg();
      hash = (37 * hash) + KEYMSG_FIELD_NUMBER;
      hash = (53 * hash) + getKeyMsg().hashCode();
      hash = (37 * hash) + VALUEMSG_FIELD_NUMBER;
      hash = (53 * hash) + getValueMsg().hashCode();
      hash = (37 * hash) + IDMSG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIdMsg());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static shared.messages.ProtoKVMessage.KVProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shared.messages.ProtoKVMessage.KVProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shared.messages.ProtoKVMessage.KVProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shared.messages.ProtoKVMessage.KVProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shared.messages.ProtoKVMessage.KVProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shared.messages.ProtoKVMessage.KVProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shared.messages.ProtoKVMessage.KVProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static shared.messages.ProtoKVMessage.KVProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static shared.messages.ProtoKVMessage.KVProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static shared.messages.ProtoKVMessage.KVProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static shared.messages.ProtoKVMessage.KVProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static shared.messages.ProtoKVMessage.KVProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(shared.messages.ProtoKVMessage.KVProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Defining the message format 
     * </pre>
     *
     * Protobuf type {@code shared.messages.KVProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:shared.messages.KVProto)
        shared.messages.ProtoKVMessage.KVProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return shared.messages.ProtoKVMessage.internal_static_shared_messages_KVProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return shared.messages.ProtoKVMessage.internal_static_shared_messages_KVProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                shared.messages.ProtoKVMessage.KVProto.class, shared.messages.ProtoKVMessage.KVProto.Builder.class);
      }

      // Construct using shared.messages.ProtoKVMessage.KVProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        statusMsg_ = 0;

        keyMsg_ = "";

        valueMsg_ = "";

        idMsg_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return shared.messages.ProtoKVMessage.internal_static_shared_messages_KVProto_descriptor;
      }

      @java.lang.Override
      public shared.messages.ProtoKVMessage.KVProto getDefaultInstanceForType() {
        return shared.messages.ProtoKVMessage.KVProto.getDefaultInstance();
      }

      @java.lang.Override
      public shared.messages.ProtoKVMessage.KVProto build() {
        shared.messages.ProtoKVMessage.KVProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public shared.messages.ProtoKVMessage.KVProto buildPartial() {
        shared.messages.ProtoKVMessage.KVProto result = new shared.messages.ProtoKVMessage.KVProto(this);
        result.statusMsg_ = statusMsg_;
        result.keyMsg_ = keyMsg_;
        result.valueMsg_ = valueMsg_;
        result.idMsg_ = idMsg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof shared.messages.ProtoKVMessage.KVProto) {
          return mergeFrom((shared.messages.ProtoKVMessage.KVProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(shared.messages.ProtoKVMessage.KVProto other) {
        if (other == shared.messages.ProtoKVMessage.KVProto.getDefaultInstance()) return this;
        if (other.getStatusMsg() != 0) {
          setStatusMsg(other.getStatusMsg());
        }
        if (!other.getKeyMsg().isEmpty()) {
          keyMsg_ = other.keyMsg_;
          onChanged();
        }
        if (!other.getValueMsg().isEmpty()) {
          valueMsg_ = other.valueMsg_;
          onChanged();
        }
        if (other.getIdMsg() != 0L) {
          setIdMsg(other.getIdMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        shared.messages.ProtoKVMessage.KVProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (shared.messages.ProtoKVMessage.KVProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int statusMsg_ ;
      /**
       * <code>uint32 statusMsg = 1;</code>
       * @return The statusMsg.
       */
      @java.lang.Override
      public int getStatusMsg() {
        return statusMsg_;
      }
      /**
       * <code>uint32 statusMsg = 1;</code>
       * @param value The statusMsg to set.
       * @return This builder for chaining.
       */
      public Builder setStatusMsg(int value) {
        
        statusMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 statusMsg = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusMsg() {
        
        statusMsg_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object keyMsg_ = "";
      /**
       * <code>string keyMsg = 2;</code>
       * @return The keyMsg.
       */
      public java.lang.String getKeyMsg() {
        java.lang.Object ref = keyMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keyMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string keyMsg = 2;</code>
       * @return The bytes for keyMsg.
       */
      public com.google.protobuf.ByteString
          getKeyMsgBytes() {
        java.lang.Object ref = keyMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string keyMsg = 2;</code>
       * @param value The keyMsg to set.
       * @return This builder for chaining.
       */
      public Builder setKeyMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keyMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string keyMsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyMsg() {
        
        keyMsg_ = getDefaultInstance().getKeyMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string keyMsg = 2;</code>
       * @param value The bytes for keyMsg to set.
       * @return This builder for chaining.
       */
      public Builder setKeyMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        keyMsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object valueMsg_ = "";
      /**
       * <code>string valueMsg = 3;</code>
       * @return The valueMsg.
       */
      public java.lang.String getValueMsg() {
        java.lang.Object ref = valueMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          valueMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string valueMsg = 3;</code>
       * @return The bytes for valueMsg.
       */
      public com.google.protobuf.ByteString
          getValueMsgBytes() {
        java.lang.Object ref = valueMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          valueMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string valueMsg = 3;</code>
       * @param value The valueMsg to set.
       * @return This builder for chaining.
       */
      public Builder setValueMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        valueMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string valueMsg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValueMsg() {
        
        valueMsg_ = getDefaultInstance().getValueMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string valueMsg = 3;</code>
       * @param value The bytes for valueMsg to set.
       * @return This builder for chaining.
       */
      public Builder setValueMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        valueMsg_ = value;
        onChanged();
        return this;
      }

      private long idMsg_ ;
      /**
       * <code>uint64 idMsg = 4;</code>
       * @return The idMsg.
       */
      @java.lang.Override
      public long getIdMsg() {
        return idMsg_;
      }
      /**
       * <code>uint64 idMsg = 4;</code>
       * @param value The idMsg to set.
       * @return This builder for chaining.
       */
      public Builder setIdMsg(long value) {
        
        idMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 idMsg = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdMsg() {
        
        idMsg_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:shared.messages.KVProto)
    }

    // @@protoc_insertion_point(class_scope:shared.messages.KVProto)
    private static final shared.messages.ProtoKVMessage.KVProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new shared.messages.ProtoKVMessage.KVProto();
    }

    public static shared.messages.ProtoKVMessage.KVProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KVProto>
        PARSER = new com.google.protobuf.AbstractParser<KVProto>() {
      @java.lang.Override
      public KVProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KVProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KVProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KVProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public shared.messages.ProtoKVMessage.KVProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shared_messages_KVProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shared_messages_KVProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037shared/messages/KVMessage.proto\022\017share" +
      "d.messages\"M\n\007KVProto\022\021\n\tstatusMsg\030\001 \001(\r" +
      "\022\016\n\006keyMsg\030\002 \001(\t\022\020\n\010valueMsg\030\003 \001(\t\022\r\n\005id" +
      "Msg\030\004 \001(\004B!\n\017shared.messagesB\016ProtoKVMes" +
      "sageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_shared_messages_KVProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_shared_messages_KVProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shared_messages_KVProto_descriptor,
        new java.lang.String[] { "StatusMsg", "KeyMsg", "ValueMsg", "IdMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
